
ALTER TABLE `INVIO_TS` ADD COLUMN `tsUsername` VARCHAR(40);

ALTER TABLE `INVIO_TS` ADD COLUMN `tsPinCode` VARCHAR(40);

ALTER TABLE `INVIO_TS` ADD COLUMN `tsPasssord` VARCHAR(40);

ALTER TABLE `INVIO_TS` ADD COLUMN `tsCodAsl` VARCHAR(3);

ALTER TABLE `INVIO_TS` ADD COLUMN `tsCodRegione` VARCHAR(3);

ALTER TABLE `INVIO_TS` ADD COLUMN `tsCfProprietario` VARCHAR(16);

ALTER TABLE `INVIO_TS` ADD COLUMN `tsPivaProprietario` VARCHAR(11);

ALTER TABLE `INVIO_TS` ADD COLUMN `tsTipoSoggetto` CHAR(1);
 



ALTER TABLE `INVIO_TS` MODIFY `tsTipoSoggetto` INTEGER;
