
ALTER TABLE  [INVIO_TS] ADD  tsUsername VARCHAR(40)
GO

ALTER TABLE  [INVIO_TS] ADD  tsPinCode VARCHAR(40)
GO

ALTER TABLE  [INVIO_TS] ADD  tsPasssord VARCHAR(40)
GO

ALTER TABLE  [INVIO_TS] ADD  tsCodAsl VARCHAR(3)
GO

ALTER TABLE  [INVIO_TS] ADD  tsCodRegione VARCHAR(3)
GO

ALTER TABLE  [INVIO_TS] ADD  tsCfProprietario VARCHAR(16)
GO

ALTER TABLE  [INVIO_TS] ADD  tsPivaProprietario VARCHAR(11)
GO

ALTER TABLE  [INVIO_TS] ADD  tsTipoSoggetto INTEGER
GO

